apiVersion: v1
kind: Service
metadata:
  name: keda-add-ons-http-interceptor-proxy
  labels:
    {{ include "keda-http-addon-example.labels" . | nindent 4 }}
spec:
  type: ExternalName
  externalName: keda-add-ons-http-interceptor-proxy.keda
  ports:
    - name: http
      port: {{ .Values.service.proxyPort }}
      protocol: TCP
      targetPort: {{ .Values.keda.http.interceptor.port }}