{{- if .Values.deploymentToZero -}}
kind: HTTPScaledObject
apiVersion: http.keda.sh/v1alpha1
metadata:
  name: keda-example
  labels:
    app.kubernetes.io/name: keda-example
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  hosts:
    - "keda-example.local"
  scalingMetric:
    requestRate:
      granularity: 1s
      targetValue: 1
      window: 1m
  scaleTargetRef:
    name: keda-example
    kind: Deployment
    apiVersion: apps/v1
    service: keda-example
    port: 0
  replicas:
    max: 1
    min: 0
{{- end -}}