{{- if .Values.deploymentToZero -}}
kind: HTTPScaledObject
apiVersion: http.keda.sh/v1alpha1
metadata:
  name: {{ include "keda-http-addon-example.fullname" . }}
  labels:
    {{ include "keda-http-addon-example.labels" . | nindent 4 }}
spec:
  hosts:
    {{- range $host := .Values.ingress.hosts }}
    - {{ $host | quote }}
    {{- end }}
  scalingMetric:
    requestRate:
      granularity: 1s
      targetValue: 1
      window: 1m
  scaleTargetRef:
    name: {{ include "keda-http-addon-example.fullname" . }}
    kind: Deployment
    apiVersion: apps/v1
    service: {{ include "keda-http-addon-example.fullname" . }}
    port: {{ .Values.service.port }}
  replicas:
    max: 1
    min: 0
{{- end -}}